version: '3.8'

services:
  db:
    image: mysql:8
    platform: linux/amd64
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT

  book-store:
    build: .
    container_name: book-store
    env_file: ./.env
    environment:
      - spring.datasource.url=$MYSQLDB_DATABASE_URL
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - db
